# default server port
server.port=9080
# default error page disable
server.error.whitelabel.enabled=false
# livereload
spring.devtools.livereload.enabled = true

# thymeleaf config
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
#spring.thymeleaf.check-template-location=true


# log4j config
logging.config=classpath:log4j2.xml

# index url
home.index.url=/