CREATE TABLE "TB_DIAG_DB" (
		DIAG_DB_ID	VARCHAR(50)	PRIMARY KEY	COMMENT '대상DBID',
        USR_ID	VARCHAR(300)    NOT NULL	COMMENT '사용자ID',
		DIAG_DB_NM	VARCHAR(200)	NOT NULL	COMMENT 'DB명',
		DIAG_DB_CN	VARCHAR(4000)	NULL	COMMENT 'DB설명',
		DIAG_DB_TYPE	VARCHAR(20)	NOT NULL	COMMENT 'DB유형',
		DIAG_DB_HOST	VARCHAR(50)	NOT NULL	COMMENT 'DB호스트',
		DIAG_DB_PORT	NUMBER(10,0)	NOT NULL	COMMENT 'DB포트',
		DIAG_DB_SERVICE_NM	VARCHAR(200)	NOT NULL	COMMENT 'DB서비스명',
		DIAG_DB_USER_NM	VARCHAR(100)	NULL	COMMENT 'DB유저명',
		DIAG_DB_PW	VARCHAR(200)	NULL	COMMENT 'DB패스워드',
		DIAG_DB_VERSION	VARCHAR(100)	NULL	COMMENT 'DB버전',
		DIAG_DB_CHARSET	VARCHAR(100)	NULL	COMMENT 'DB케릭터셋',
		DIAG_DB_CONSTR	VARCHAR(4000)	NULL	COMMENT 'DB연결문자',
        ERR_RSLT_LIMT_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '오류결과건수제한여부',
        ERR_RSLT_LIMT_CNT	NUMBER(10,0)	NOT NULL	DEFAULT 1000	COMMENT '오류결과제한건수',
        PYSC_DB_TBL_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '물리DB기준테이블현행화',
        PYSC_DB_COL_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '물리DB기준컬럼현행화',
        TBL_DEF_TBL_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '테이블정의서기준테이블현행화',
        COL_DEF_COL_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '컬럼정의서기준컬럼현행화',
        STD_CMP_YN	CHAR(1)	NOT NULL	DEFAULT 'Y'	COMMENT '표준용어준수(+도메인)',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
        CONSTRAINT TB_DIAG_DB_PK PRIMARY KEY(DIAG_DB_ID)
		);
CREATE TABLE "TB_DIAG_TBL" (
        DIAG_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상테이블ID',
		DIAG_DB_ID	VARCHAR(50)	NOT NULL	COMMENT '대상DBID',
		DIAG_TBL_NM	VARCHAR(200)	NOT NULL	COMMENT '테이블명',
		DIAG_TBL_CMNT	VARCHAR(4000)	NULL	COMMENT '코멘트',
		COLC_YN	CHAR(1)	NOT NULL	DEFAULT 'Y' COMMENT '수집여부',
        DIAG_EXC_YN CHAR(1) NOT NULL   DEFAULT 'N' COMMENT '진단제외여부',
        DIAG_EXC_CN VARCHAR(4000)	NULL	COMMENT '진단제외사유',
        DIAG_SMPL_YN CHAR(1) NOT NULL	DEFAULT 'N' COMMENT '샘플링여부',
        DIAG_SMPL_CNT NUMBER(10,0) NULL COMMENT '샘플링건수',
		DIAG_SQL    VARCHAR(4000) NULL	COMMENT '검색조건SQL',
        DIAG_SMPL_SQL_CN VARCHAR(4000)	NULL	COMMENT '샘플링및검색조건사유',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
		CONSTRAINT TB_DIAG_TBL_PK PRIMARY KEY(DIAG_TBL_ID, DIAG_DB_ID)
		);
CREATE TABLE "TB_DIAG_COL" (					
		DIAG_COL_ID	VARCHAR(50) NOT NULL COMMENT '대상컬럼ID',
		DIAG_DB_ID	VARCHAR(50)	NOT NULL	COMMENT '대상DBID',
		DIAG_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상테이블ID',
		DIAG_COL_NM	VARCHAR(200)	NOT NULL	COMMENT '컬럼명',
		DIAG_COL_CMNT	VARCHAR(4000)	NULL	COMMENT '코멘트',
		DIAG_COL_TYPE	VARCHAR(50)	NOT NULL	COMMENT '데이터타입',
		DIAG_COL_SIZE	NUMBER(10,0)	NOT NULL	COMMENT '데이터사이즈',
        DIAG_COL_DFLT	VARCHAR(50)	    NULL	COMMENT '기본값',
		DIAG_COL_DCM	NUMBER(10,0)	NULL	COMMENT '소수자릿수',
		DIAG_COL_NULL_YN	CHAR(1)	NOT NULL	COMMENT 'NULL허용여부',
		DIAG_COL_PK_YN	CHAR(1)	NOT NULL	COMMENT '기본키여부',
		DIAG_COL_ESS_YN	CHAR(1)	NULL	COMMENT '필수여부',
		DIAG_COL_ESS_DT	TIMESTAMP	NULL	COMMENT '필수여부적용일시',
		DIAG_COL_VT_PK_YN	CHAR(1)	NULL	COMMENT '가상PK여부',
		DIAG_COL_PK_SEQ	NUMBER(3,0)	NULL	COMMENT 'PK순서',
		DIAG_COL_PK_SEQ_DT	TIMESTAMP	NULL	COMMENT 'PK순서적용일시',
        DIAG_COL_OPN	VARCHAR(4000)	NULL	COMMENT '진단의견',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
        CONSTRAINT TB_DIAG_COL_PK PRIMARY KEY(DIAG_COL_ID, DIAG_TBL_ID)
		);
CREATE TABLE "TB_PROF_RSLT" (					
		DIAG_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상컬럼ID',
		PROF_RSLT_ID	VARCHAR(50)	NOT NULL	COMMENT '프로파일링결과ID',
		TOT_CNT	NUMBER(10,0)	NOT NULL	COMMENT '전체건수',
		NULL_CNT	NUMBER(10,0)	NOT NULL	COMMENT 'NULL건수',
		NON_NULL_CNT	NUMBER(10,0)	NOT NULL	COMMENT 'NON-NULL건수',
		SGL_DT_CNT	NUMBER(10,0)	NOT NULL	COMMENT '단일데이터건수',
		DUP_DT_CNT	NUMBER(10,0)	NOT NULL	COMMENT '중복데이터건수',
		MIN_LEN	NUMBER(10,0)	NOT NULL	COMMENT '최소길이',
		MAX_LEN	NUMBER(10,0)	NOT NULL	COMMENT '최대길이',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		CONSTRAINT TB_PROF_RSLT_PK PRIMARY KEY(DIAG_COL_ID, PROF_RSLT_ID)					
		);					
CREATE TABLE "TB_PROF_RSLT_SMPL_DT" (					
		PROF_RSLT_ID	VARCHAR(50)	NOT NULL	COMMENT '프로파일링결과ID',
		DIAG_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상컬럼ID',
		SMPL_DT_ID	VARCHAR(50)	NOT NULL	COMMENT '샘플데이터ID',
		SMPL_DT_CN	VARCHAR(4000)	NULL	COMMENT '샘플데이터내용',
		SMPL_DT_PTN	VARCHAR(4000)	NULL	COMMENT '데이터패턴',
        NULL_YN	CHAR(1)	NOT NULL	COMMENT 'NULL여부',
        ENG_CNT	NUMBER(10,0)	NOT NULL	COMMENT '영문포함건수',
        KOR_CNT	NUMBER(10,0)	NOT NULL	COMMENT '한글포함건수',
        NUM_CNT	NUMBER(10,0)	NOT NULL	COMMENT '숫자포함건수',
        GAP_CNT	NUMBER(10,0)	NOT NULL	COMMENT '공백포함건수',
        SYB_CNT	NUMBER(10,0)	NOT NULL	COMMENT '특수문자포함건수',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		CONSTRAINT TB_PROF_RSLT_SMPL_DT_PK PRIMARY KEY(PROF_RSLT_ID, DIAG_COL_ID, SMPL_DT_ID)					
		);					
CREATE TABLE "TB_VRFC_RULE_REL" (					
		VRFC_RULE_ID	VARCHAR(50)	PRIMARY KEY	COMMENT '검증룰ID',
		COMB_VRFC_RULE_ID	VARCHAR(50)	NOT NULL	COMMENT '조합검증룰ID',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시'
		);					
CREATE TABLE "TB_VRFC_CD" (
	DIAG_DB_ID CHARACTER VARYING(50) NOT NULL COMMENT '대상DBID',
	VRFC_CD_ID CHARACTER VARYING(50) NOT NULL COMMENT '검증코드ID',
	CD_NM CHARACTER VARYING(200) NOT NULL COMMENT '검증코드명',
	CD_CN CHARACTER VARYING(4000) NOT NULL COMMENT '코드설명',
	CD_TYP_CD CHARACTER(2) NOT NULL COMMENT '코드유형코드',
	CD_MNG_CD CHARACTER(2) COMMENT '코드관리방법코드',
	CD_EXTC_SQL CHARACTER VARYING(4000) COMMENT '코드추출SQL(SELECT)',
	ERR_EXC_DT CHARACTER VARYING(4000) COMMENT '오류제외데이터',
	ERR_EXC_DT_DIV CHARACTER VARYING(20) COMMENT '오류제외데이터구분자',
	CLS_CD_COL CHARACTER VARYING(200) COMMENT '분류코드컬럼',
	CLS_CD_NM_COL CHARACTER VARYING(200) COMMENT '분류코드명컬럼',
	CM_CD_COL CHARACTER VARYING(200) COMMENT '공통코드컬럼',
	CM_CD_NM_COL CHARACTER VARYING(200) COMMENT '공통코드명컬럼',
	REG_ID CHARACTER VARYING(50) NOT NULL COMMENT '등록자ID',
	REG_DT TIMESTAMP NOT NULL COMMENT '등록일시',
	MDFCN_ID CHARACTER VARYING(50) COMMENT '수정자ID',
	MDFCN_DT TIMESTAMP COMMENT '수정일시',
	CONSTRAINT TB_VRFC_CD_PK PRIMARY KEY (DIAG_DB_ID,VRFC_CD_ID)
);
CREATE TABLE "TB_VRFC_CD_DT" (
	VRFC_CD_ID CHARACTER VARYING(50) NOT NULL COMMENT '검증코드ID',
	VRFC_CD_DT_ID CHARACTER VARYING(50) NOT NULL COMMENT '검증코드데이터ID',
	CLS_CD CHARACTER VARYING(200) COMMENT '분류코드',
	CLS_CD_NM CHARACTER VARYING(200) COMMENT '분류코드명',
	CM_CD CHARACTER VARYING(200) NOT NULL COMMENT '공통코드',
	CM_CD_NM CHARACTER VARYING(200) NOT NULL COMMENT '공통코드명',
	REG_ID CHARACTER VARYING(50) NOT NULL COMMENT '등록자ID',
	REG_DT TIMESTAMP NOT NULL COMMENT '등록일시',
	CONSTRAINT TB_VRFC_CD_DT_PK PRIMARY KEY (VRFC_CD_DT_ID,VRFC_CD_ID)
);
CREATE TABLE "TB_VRFC_MDL_TBL" (
		DIAG_DB_ID CHARACTER VARYING(50) NOT NULL COMMENT '대상DBID',
		VRFC_MDL_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '검증모델테이블ID',
		SCM_NM	VARCHAR(200)	NOT NULL	COMMENT '스키마명',
		TBL_NM	VARCHAR(200)	NOT NULL	COMMENT '테이블명',
		TBL_CMNT	VARCHAR(4000)	NULL	COMMENT '코멘트',
		COL_CNT	NUMERIC(10,0)	NULL	COMMENT '컬럼수',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		CONSTRAINT TB_VRFC_MDL_TBL_PK PRIMARY KEY (DIAG_DB_ID,VRFC_MDL_TBL_ID)
		);					
CREATE TABLE "TB_VRFC_MDL_COL" (		
		DIAG_DB_ID CHARACTER VARYING(50) NOT NULL COMMENT '대상DBID',
		VRFC_MDL_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '검증모델테이블ID',
		VRFC_MDL_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '검증모델컬럼ID',
		SCM_NM	VARCHAR(200)	NOT NULL	COMMENT '스키마명',
		COL_NM	VARCHAR(200)	NOT NULL	COMMENT '컬럼명',
		COL_CMNT	VARCHAR(4000)	NULL	COMMENT '코멘트',
		COL_DT_TYP	VARCHAR(100)	NOT NULL	COMMENT '데이터타입',
		COL_LEN	NUMERIC(10,0)	NULL	COMMENT '전체길이',
		COL_PNT_LEN	NUMERIC(10,0)	NULL	COMMENT '소수점길이',
		COL_NULL_YN	CHAR(1)	NULL	COMMENT 'NULL허용여부',
		COL_PK_YN	CHAR(1)	NULL	COMMENT 'PK여부',
		COL_PK_SEQ	NUMERIC(10,0)	NULL	COMMENT 'PK순번',
		COL_FK_YN	CHAR(1)	NULL	COMMENT 'FK여부',
		STD_CMP_YN	CHAR(1)	NULL	COMMENT '표준준수여부',
		STD_CMP_INS_CN	VARCHAR(4000)	NULL	COMMENT '표준준수점검내용',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		CONSTRAINT TB_VRFC_MDL_COL_PK PRIMARY KEY (DIAG_DB_ID,VRFC_MDL_TBL_ID,VRFC_MDL_COL_ID)
		);					
CREATE TABLE "TB_VRFC_RULE_HIS" (					
		VRFC_RULE_ID	VARCHAR(50)	NOT NULL	COMMENT '검증룰ID',
		VRFC_RULE_HIS_ID	VARCHAR(50)	NOT NULL	COMMENT '검증룰이력ID',
		VRFC_RULE_NM	VARCHAR(200)	NOT NULL	COMMENT '검증룰명',
		VRFC_RULE_CN	VARCHAR(4000)	NOT NULL	COMMENT '검증룰설명',
		DMN_CD	CHAR(2)	NOT NULL	COMMENT '도메인코드',
		DIAG_TYP_CD	CHAR(2)	NOT NULL	COMMENT '진단유형코드',
		YN_VAL	VARCHAR(1000)	NULL	COMMENT '여부값',
		MIN_VAL	NUMBER(10,0)	NULL	COMMENT '최소값',
		MIN_VAL_INCL_YN	CHAR(1)	NULL	COMMENT '최소값포함여부',
		MAX_VAL	NUMBER(10,0)	NULL	COMMENT '최대값',
		MAX_VAL_INCL_YN	CHAR(1)	NULL	COMMENT '최대값포함여부',
		DT_FRMT	VARCHAR(100)	NULL	COMMENT '날짜포맷',
		FRMT_CD	CHAR(1)	NULL	COMMENT '형식지정코드',
		FRMT_CN	VARCHAR(4000)	NULL	COMMENT '형식지정내용',
		COMB_YN	CHAR(1)	NULL	COMMENT '조합사용여부',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
		CONSTRAINT TB_VRFC_RULE_HIS_PK PRIMARY KEY(VRFC_RULE_ID, VRFC_RULE_HIS_ID)					
		);					
CREATE TABLE "TB_VRFC_CD_HIS" (					
		VRFC_CD_ID	VARCHAR(50)	NOT NULL	COMMENT '검증코드ID',
		VRFC_CD_HIS_ID	VARCHAR(50)	NOT NULL	COMMENT '검증코드이력ID',
		CD_NM	VARCHAR(200)	NOT NULL	COMMENT '검증코드명',
		CD_CN	VARCHAR(4000)	NOT NULL	COMMENT '코드설명',
		CD_TYP_CD	CHAR(2)	NOT NULL	COMMENT '코드유형',
		CD_MNG_CD	CHAR(2)	NULL	COMMENT '코드관리방법코드',
		CD_EXTC_SQL	VARCHAR(4000)	NULL	COMMENT '코드추출SQL',
		ERR_EXC_CN	VARCHAR(4000)	NULL	COMMENT '오류제외데이터',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
		CONSTRAINT TB_VRFC_CD_HIS_PK PRIMARY KEY(VRFC_CD_ID, VRFC_CD_HIS_ID)					
		);					
CREATE TABLE "TB_VRFC_STD_DMN" (					
		DIAG_DB_ID CHARACTER VARYING(50) NOT NULL COMMENT '대상DBID',
		VRFC_STD_DMN_ID	VARCHAR(50)	NOT NULL COMMENT '검증표준도메인ID',
		DMN_NM	VARCHAR(200)	NOT NULL	COMMENT '도메인명',
		DMN_CN	VARCHAR(200)	NOT NULL	COMMENT '도메인설명',
		DT_TYP	VARCHAR(4000)	NULL	COMMENT '데이터타입',
		DGT_CNT	NUMERIC(10,0)	NULL	COMMENT '전체자리수',
		COL_PNT_LEN	NUMERIC(10,0)	NULL	COMMENT '소수점길이',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		CONSTRAINT TB_VRFC_STD_DMN_PK PRIMARY KEY(DIAG_DB_ID, VRFC_STD_DMN_ID)					
		);					
CREATE TABLE "TB_VRFC_STD_TERM" (
		DIAG_DB_ID CHARACTER VARYING(50) NOT NULL COMMENT '대상DBID',
		VRFC_STD_TERM_ID	VARCHAR(50)	NOT NULL COMMENT '검증표준용어ID',
		VRFC_STD_DMN_ID	VARCHAR(50)	NOT NULL COMMENT '검증표준도메인ID',
		TERM_NM	VARCHAR(200)	NOT NULL	COMMENT '용어명',
		ENG_ABB_NM	VARCHAR(200)	NOT NULL	COMMENT '영문약어명',
		TERM_CN	VARCHAR(4000)	NULL	COMMENT '용어설명',
		MPNG_YN	CHAR(1)	NULL	COMMENT '매핑여부',
		MPNG_TERM_NM	VARCHAR(200)	NULL	COMMENT '매핑용어명',
		MPNG_PYSC_NM	VARCHAR(200)	NULL	COMMENT '매핑물리용어명',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		CONSTRAINT TB_VRFC_STD_TERM_PK PRIMARY KEY(DIAG_DB_ID, VRFC_STD_TERM_ID)			
		);					
CREATE TABLE "TB_DIAG_COL_RULE_REL" (					
		DIAG_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상컬럼ID',
		VRFC_ID	VARCHAR(50)	NOT NULL	COMMENT '검증매핑ID',
        VRFC_TYP_CD CHAR(2) NOT NULL    COMMENT '검증유형코드',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		CONSTRAINT TB_DIAG_COL_RULE_REL_PK PRIMARY KEY(DIAG_COL_ID, VRFC_ID)
		);					
CREATE TABLE "TB_VRFC_RULE" (					
		VRFC_RULE_ID	VARCHAR(50)	PRIMARY KEY	COMMENT '검증룰ID',
		VRFC_RULE_NM	VARCHAR(200)	NOT NULL	COMMENT '검증룰명',
		VRFC_RULE_CN	VARCHAR(4000)	NOT NULL	COMMENT '검증룰설명',
		DMN_CD	CHAR(2)	NOT NULL	COMMENT '도메인코드',
		DIAG_TYP_CD	CHAR(2)	NOT NULL	COMMENT '진단유형코드',
		YN_VAL	VARCHAR(1000)	NULL	COMMENT '여부값',
		MIN_VAL	VARCHAR(100)	NULL	COMMENT '최소값',
		MIN_VAL_INCL_YN	CHAR(1)	NULL	COMMENT '최소값포함여부',
		MAX_VAL	VARCHAR(100)	NULL	COMMENT '최대값',
		MAX_VAL_INCL_YN	CHAR(1)	NULL	COMMENT '최대값포함여부',
		DT_FRMT	VARCHAR(100)	NULL	COMMENT '날짜포맷',
		FRMT_CD	CHAR(2)	NULL	COMMENT '형식지정코드',
		FRMT_CN	VARCHAR(4000)	NULL	COMMENT '형식지정내용',
		COMB_YN	CHAR(1)	NULL	COMMENT '조합사용여부',
		ERR_EXC_DT	VARCHAR(4000)	NULL	COMMENT '오류제외데이터',
		ERR_EXC_DT_DIV	VARCHAR(20)	NULL	COMMENT '오류제외데이터구분자',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시'
		);					
CREATE TABLE "TB_BIZ_RULE" (					
		DIAG_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상테이블ID',
		DIAG_DB_ID	VARCHAR(50)	NOT NULL	COMMENT '대상DBID',
		BIZ_RULE_ID	VARCHAR(50)	NOT NULL	COMMENT '업무규칙ID',
		ANLYS_AREA_CD	CHAR(2)	NOT NULL	COMMENT '분석영역',
		BIZ_RULE_NM	VARCHAR(200)	NOT NULL	COMMENT '업무규칙명',
		BIZ_RULE_CN	VARCHAR(4000)	NULL	COMMENT '업무규칙설명',
		USE_YN	CHAR(1)	NOT NULL	COMMENT '사용여부',
		ERR_DATA_EXT_SQL	VARCHAR(4000)	NOT NULL	COMMENT '오류데이터추출SQL',
		DIAG_TOT_CNT_SQL	VARCHAR(4000)	NOT NULL	COMMENT '대상전체건수SQL',
		ERR_DATA_CNT_SQL	VARCHAR(4000)	NULL	COMMENT '오류데이터건수SQL',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		MDFCN_ID	VARCHAR(50)	NULL	COMMENT '수정자ID',
		MDFCN_DT	TIMESTAMP	NULL	COMMENT '수정일시',
		CONSTRAINT TB_BIZ_RULE_PK PRIMARY KEY(BIZ_RULE_ID, DIAG_DB_ID, DIAG_TBL_ID)					
		);					
CREATE TABLE "TB_REF_INTG" (					
		DIAG_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상테이블ID',
		DIAG_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '대상컬럼ID',
		DIAG_JOIN_SEQ	NUMBER(10,0)	NULL	COMMENT '대상조인순서',
		REF_TBL_ID	VARCHAR(50)	NOT NULL	COMMENT '참조테이블ID',
		REF_COL_ID	VARCHAR(50)	NOT NULL	COMMENT '참조컬럼ID',
		REF_JOIN_SEQ	NUMBER(10,0)	NULL	COMMENT '참조조인순서',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID',
		CONSTRAINT TB_REF_INTG_PK PRIMARY KEY(DIAG_TBL_ID, DIAG_COL_ID)
		);					
CREATE TABLE "TB_USER" (					
		USR_ID	VARCHAR(300)	PRIMARY KEY	COMMENT '사용자ID',
		USR_NM	VARCHAR(300)	NOT NULL	COMMENT '사용자명',
		USR_PW	VARCHAR(200)	NOT NULL	COMMENT '비밀번호',
		ORG_NM	VARCHAR(200)	NULL	COMMENT '기관',
		DEPT_NM	VARCHAR(200)	NULL	COMMENT '부서',
		EMAIL	VARCHAR(500)	NULL	COMMENT '이메일',
		PHONE	VARCHAR(50)	NULL	COMMENT '연락처',
		REG_DT	TIMESTAMP	NOT NULL	COMMENT '등록일시',
		REG_ID	VARCHAR(50)	NOT NULL	COMMENT '등록자ID'
		);
CREATE TABLE "TB_CODE" (
	CODE_ID VARCHAR(100) NOT NULL	COMMENT '코드ID',
	CODE_NM VARCHAR(500) NOT NULL	COMMENT '코드명',
	DTL_CODE_ID VARCHAR(100) NOT NULL	COMMENT '상세코드ID',
	DTL_CODE_NM VARCHAR(500) NOT NULL	COMMENT '상세코드명',
	REG_DT TIMESTAMP NOT NULL	COMMENT '등록일시',
	REG_ID VARCHAR(50) NOT NULL	COMMENT '등록자ID',
	CONSTRAINT TB_CODE_PK PRIMARY KEY(CODE_ID, DTL_CODE_ID)
);
CREATE TABLE "TB_DIAG_JOB_DTL"(
	DIAG_JOB_DTL_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB상세ID',
	DIAG_JOB_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOBID',
	DIAG_DB_ID	VARCHAR(50)	NOT NULL COMMENT '대상DBID',
	DIAG_TBL_ID	VARCHAR(50)	COMMENT '대상테이블ID',
	DIAG_COL_ID	VARCHAR(50) COMMENT '대상컬럼ID',
	DIAG_JOB_TYP_CD CHAR(2) COMMENT '진단JOB구분코드',
	VRFC_RULE_ID	VARCHAR(200)	NOT NULL COMMENT '검증룰ID',
	REG_DT	TIMESTAMP	NOT NULL COMMENT '등록일시',
	REG_ID	VARCHAR(50)	NULL COMMENT '등록자ID',
	CONSTRAINT TB_DIAG_JOB_DTL_PK PRIMARY KEY(DIAG_JOB_ID, DIAG_JOB_DTL_ID)
);
CREATE TABLE "TB_DIAG_JOB_RSLT"(
	DIAG_JOB_DTL_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB상세ID',
	DIAG_JOB_RSLT_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB결과ID',
	TOT_CNT	NUMBER(10,0)	NOT NULL COMMENT '전체건수',
	ERR_CNT	NUMBER(10,0)	NOT NULL COMMENT '오류건수',
	DIAG_ORDR	NUMBER(10,0)	NOT NULL COMMENT '진단차수',
	EXEC_DT	TIMESTAMP	NOT NULL COMMENT '수행시작일시',
	EXEC_TIME	VARCHAR(20)	NOT NULL COMMENT '수행시간',
	EXEC_STTS_CD	CHAR(2)	NOT NULL COMMENT '수행상태코드',
	EXEC_CLS_CD	CHAR(2)	NOT NULL COMMENT '실행구분코드',
	ERR_DATA_EXT_SQL	VARCHAR(4000) COMMENT '오류데이터추출SQL',
	DIAG_TOT_CNT_SQL	VARCHAR(4000) COMMENT '진단대상전체건수SQL',
	REG_DT	TIMESTAMP	NOT NULL COMMENT '등록일시',
	REG_ID	VARCHAR(50)	NULL COMMENT '등록자ID',
	CONSTRAINT TB_DIAG_JOB_RSLT_PK PRIMARY KEY(DIAG_JOB_DTL_ID, DIAG_JOB_RSLT_ID)
);
CREATE TABLE "TB_DIAG_JOB"(
	DIAG_JOB_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOBID',
	DIAG_DB_ID	VARCHAR(50)	NOT NULL COMMENT '대상DBID',
	DIAG_JOB_NM	VARCHAR(50)	NOT NULL COMMENT '진단JOB명',
	DIAG_JOB_CN	VARCHAR(4000)	COMMENT '진단JOB설명',
	EXEC_CYCLE	CHAR(2)	COMMENT '실행주기',
	EXEC_BASE_DT	TIMESTAMP	COMMENT '실행기준일',
	EXEC_HOUR	NUMBER(5,0)	 COMMENT '실행시간',
	EXEC_MIN	NUMBER(5,0)	 COMMENT '실행분',
	USE_YN	CHAR(1)	NOT NULL COMMENT '사용여부',
	DEF_YN	CHAR(1)	NOT NULL COMMENT '기본여부',
	REG_DT	TIMESTAMP	NOT NULL COMMENT '등록일시',
	REG_ID	VARCHAR(50)	NULL COMMENT '등록자ID',
	CONSTRAINT TB_DIAG_JOB_PK PRIMARY KEY(DIAG_DB_ID, DIAG_JOB_ID)
);
CREATE TABLE "TB_DIAG_JOB_RSLT_VAL"(
	DIAG_JOB_RSLT_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB결과ID',
	DIAG_JOB_DTL_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB상세ID',
	DIAG_JOB_RSLT_VAL_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB결과값ID',
	ERR_DT_CN VARCHAR(4000)	NOT NULL COMMENT '오류데이터',
	REG_DT	TIMESTAMP	NOT NULL COMMENT '등록일시',
	REG_ID	VARCHAR(50)	NULL COMMENT '등록자ID',
	CONSTRAINT TB_DIAG_JOB_RSLT_VAL_PK PRIMARY KEY(DIAG_JOB_RSLT_ID, DIAG_JOB_DTL_ID, DIAG_JOB_RSLT_VAL_ID)
);
CREATE TABLE "TB_DIAG_JOB_RSLT_STD"(
	DIAG_JOB_RSLT_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB결과ID',
	DIAG_JOB_DTL_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB상세ID',
	DIAG_JOB_RSLT_STD_ID	VARCHAR(50)	NOT NULL COMMENT '진단JOB결과표준ID',
	DIAG_TBL_ID	VARCHAR(50)	COMMENT '대상테이블ID',
	DIAG_COL_ID	VARCHAR(50) COMMENT '대상컬럼ID',
	STD_CMP_YN	CHAR(1)	NULL	COMMENT '표준준수여부',
	STD_CMP_INS_CN	VARCHAR(4000)	NULL	COMMENT '표준준수점검내용',
	REG_DT	TIMESTAMP	NOT NULL COMMENT '등록일시',
	REG_ID	VARCHAR(50)	NULL COMMENT '등록자ID',
	CONSTRAINT TB_DIAG_JOB_RSLT_STD_PK PRIMARY KEY(DIAG_JOB_RSLT_ID, DIAG_JOB_DTL_ID, DIAG_JOB_RSLT_STD_ID)	
);


